### PR TITLE
Optional readonly field

### PR DESCRIPTION
**Pull request by kevinresol**
Currently, this is just a failing test for the case. I still need to figure out how to fix it. Welcome any ideas.

Error: Cannot write property at https://github.com/haxetink/tink_querystring/blob/ff9d766/src/tink/querystring/macros/GenParser.hx#L195

### CODE REVIEW

**Comment by kevinresol** [comment]
Ok I fixed it by inserting a null for the optional field and make all fields to be declared in `EObjectDecl` in one go.

There is a semantic difference compared with the implementation before. But that happens only if people use things like `Reflect.hasField` on the resulting object, which I hope is rare.

**Comment by kevinresol** [comment]
@back2dos we need to deal with this. Please see if you are ok with my fix.

**Comment by back2dos** [comment]
I prefer the solution we have in tink_json, but if it's fine for you to have that field, I guess it's ok. Might potentially lead to undesired behavior if the object is used directly for an update in a document store or some such thing.

**Review by back2dos — APPROVED** [review]

**Comment by serjek** [comment]
ETA on merging this?

**Comment by kevinresol** [comment]
> ETA on merging this?

I guess no until there is a better solution

**Comment by serjek** [comment]
Problem is that without this fix library remains incompatible with tink_core@2 and so tink_sql which is a dependant.

**Comment by grepsuzette** [comment]
> Problem is that without this fix library remains incompatible with tink_core@2 and so tink_sql which is a dependant.

I think it's the same for me, 

```
haxe_libraries/tink_querystring/0.6.0/github/8eee7f83e2f60606415ff09062423117ff839056/src/tink/querystring/macros/GenParser.hx:121: characters 26-33 : error: Cannot unify final and non-final fields
haxe_libraries/tink_querystring/0.6.0/github/8eee7f83e2f60606415ff09062423117ff839056/src/tink/querystring/macros/GenParser.hx:121: characters 26-33 : ... have: ({ name: Dynamic }) -> ...
```

Above is using something like `tink_core#2.0.1`.
It compiles fine staying with `tink_core#1.27.0`, all other libs being the most recent ones.
This is of course for a js server with tink_sql and tink_web.

**Comment by kevinresol** [comment]
will revisit this after #20

**Pull request closed without merging**
