### PR TITLE
Support dynamics/dynamic access.

### PR DESCRIPTION
**Pull request by piboistudios**
I believe this should allow for support of dynamics/dynamic access but.. admimttedly I am not entirely aware of what these macros are doing. 

The tests pass though.

This follows the pattern mentioned by Kevin on #6 

Maps not included.

### CODE REVIEW

**Comment by kevinresol** [comment]
will revisit this after #20

**Comment by piboistudios** [comment]
> will revisit this after #20

What's the status of this feature

**Comment by kevinresol** [comment]
Should be supported now

**Comment by piboistudios** [comment]
Sweet. Unrelated, but can you send me a Discord invite?

Encountered some issues with tink_streams 0.4.0 that I wanted to ask about and Gitter is down

**Pull request closed without merging**
